const nf=new Intl.NumberFormat("zh-CN");const pf=new Intl.NumberFormat("zh-CN",{style:"percent",maximumFractionDigits:1});
const state={payload:null,query:"",category:"全部分类"};
const $=id=>document.getElementById(id);const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
function date(value){const d=new Date(value);return Number.isNaN(d.getTime())?String(value||"").slice(0,10):d.toLocaleDateString("zh-CN");}
function datetime(value){if(!value)return"尚未同步";const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString("zh-CN",{hour12:false});}
function noteKey(id){return`feifan-wechat-note-${id}`}
function render(){const p=state.payload;if(!p)return;const list=p.articles||[];const sum=p.summary||{};$("articleCount").textContent=nf.format(sum.articleCount??list.length);$("readUser").textContent=nf.format(sum.readUser||0);$("shareUser").textContent=nf.format(sum.shareUser||0);$("subscribeUser").textContent=nf.format(sum.readSubscribeUser||0);$("finishRate").textContent=pf.format(sum.avgFinishRate||0);$("updatedAt").textContent=`页面读取 ${new Date().toLocaleTimeString("zh-CN",{hour12:false})}`;const sync=p.latestSync;$("syncStatus").textContent=sync?.status==="success"?"自动同步正常":sync?"最近同步需关注":"等待首次同步";$("syncTime").textContent=datetime(sync?.finishedAt);$("syncMessage").textContent=sync?.message||"新推文约每 5 分钟检查一次；传播指标按微信官方开放时间更新。";
  const top=[...list].sort((a,b)=>(b.readUser||0)-(a.readUser||0)).slice(0,5),max=Math.max(1,...top.map(x=>x.readUser||0));$("ranking").innerHTML=top.length?top.map((a,i)=>`<div class="rank-row"><span>${String(i+1).padStart(2,"0")}</span><div class="rank-copy"><b>${esc(a.title)}</b><div class="bar"><i style="width:${Math.max(3,(a.readUser||0)/max*100)}%"></i></div></div><strong>${nf.format(a.readUser||0)}</strong></div>`).join(""):'<p class="empty">等待公众号数据</p>';
  const categories=[...new Set(list.map(x=>x.category||"待分类"))].sort();$("category").innerHTML=['全部分类',...categories].map(x=>`<option${x===state.category?' selected':''}>${esc(x)}</option>`).join("");const q=state.query.trim().toLowerCase();const filtered=list.filter(a=>(state.category==="全部分类"||(a.category||"待分类")===state.category)&&(!q||`${a.title} ${a.summary} ${a.keywords}`.toLowerCase().includes(q)));$("rows").innerHTML=filtered.length?filtered.map(a=>`<tr><td><time>${esc(date(a.publishedAt))}</time><a href="${esc(a.contentUrl)}" target="_blank" rel="noreferrer">${esc(a.title)}</a><small>${esc(a.author||"创非凡AI全域服务")}</small></td><td><span class="tag">${esc(a.category||"待分类")}</span></td><td>${esc(a.summary||a.digest||"")}</td><td>${esc(a.keywords||"")}</td><td><strong class="metric">${nf.format(a.readUser||0)}</strong></td><td>${nf.format(a.shareUser||0)}</td><td>${nf.format(a.zaikanUser||0)} / ${nf.format(a.likeUser||0)}</td><td>${a.readFinishRate?pf.format(a.readFinishRate):"—"}</td><td>${esc(a.status||"已发布")}</td><td><textarea class="note" data-id="${a.id}" placeholder="输入本机运营备注">${esc(localStorage.getItem(noteKey(a.id))||"")}</textarea></td></tr>`).join(""):'<tr><td colspan="10" class="empty">暂无匹配内容</td></tr>';$("count").textContent=`共 ${filtered.length} 条内容`;document.querySelectorAll(".note").forEach(el=>el.addEventListener("input",e=>localStorage.setItem(noteKey(e.target.dataset.id),e.target.value)));}
async function load(){try{const res=await fetch(`data.json?t=${Date.now()}`,{cache:"no-store"});if(!res.ok)throw new Error(`HTTP ${res.status}`);state.payload=await res.json();$("notice").hidden=true;render()}catch(err){$("notice").textContent=`数据暂时读取失败：${err.message}`;$("notice").hidden=false}}
$("search").addEventListener("input",e=>{state.query=e.target.value;render()});$("category").addEventListener("change",e=>{state.category=e.target.value;render()});load();setInterval(load,60_000);
